#### 문자열 인덱싱

In [276]:
import pandas as pd
import numpy as np

In [277]:
alarm = pd.read_csv('./data/강원도_강원도소방본부_소방용수시설.csv', encoding = 'cp949')
df = pd.read_csv('./data/구조 종별 신고.재난 데이터.csv', encoding= 'utf-8')

In [278]:
# 데이터 화재관련 값만 추출

df = df[(df['ACDNT_CAUSE'] == '기타화재') | (df['ACDNT_CAUSE'] == '화약류') | (df['ACDNT_CAUSE'] == '방화')
        | (df['ACDNT_CAUSE'] == '폭발물') | (df['ACDNT_CAUSE'] == '화재확인')]

In [279]:
df.isnull().sum()
df = df.dropna(axis = 1) # 누락값이 있는 열 삭제

## 소방용수시설의 EMD_NM 만들기

- 재난데이터와 합치기 위해 EMD_NM를 만들어야함

In [280]:
# 소재지지번주소의 7번째 이후의 데이터를 만들어서 저장
alarm['EMD_NM'] = alarm['소재지지번주소'].str[7:]
alarm.head(5)

,시설번호,시설유형코드,시군구명,시군구코드,소재지지번주소,위도,경도,안전센터명,보호틀유무,사용가능여부,설치연도,배관깊이,출수압력,배관지름,관할기관명,데이터기준일자,EMD_NM
0,강촌001호,1,춘천시,42110,강원도 춘천시 남산면 창촌리 145-1,37.786189,127.649237,강촌안전센터,N,Y,2007,0.7,7.0,100,춘천소방서,2021-11-19,남산면 창촌리 145-1
1,강촌002호,1,춘천시,42110,강원도 춘천시 남산면 창촌리 147-1,37.786725,127.647929,강촌안전센터,N,Y,2013,0.7,8.0,100,춘천소방서,2021-11-19,남산면 창촌리 147-1
2,강촌003호,1,춘천시,42110,강원도 춘천시 남산면 창촌리 126-9,37.785523,127.646686,강촌안전센터,Y,Y,2013,0.7,8.0,100,춘천소방서,2021-11-19,남산면 창촌리 126-9
3,강촌004호,1,춘천시,42110,강원도 춘천시 남산면 창촌리 219-15,37.784756,127.643488,강촌안전센터,Y,Y,2013,0.8,8.0,100,춘천소방서,2021-11-19,남산면 창촌리 219-15
4,강촌005호,1,춘천시,42110,강원도 춘천시 남산면 창촌리 238-2,37.781550,127.643992,강촌안전센터,Y,Y,2013,0.7,5.5,100,춘천소방서,2021-11-19,남산면 창촌리 238-2

In [281]:
alarm['EMD_NM'] = alarm['EMD_NM'].str.lstrip() # 앞 공백을 제거

In [282]:
alarm['EMD_NM'].str.split(" ").head() # 공백을 기준으로 분할

0     [남산면, 창촌리, 145-1]
1     [남산면, 창촌리, 147-1]
2     [남산면, 창촌리, 126-9]
3    [남산면, 창촌리, 219-15]
4     [남산면, 창촌리, 238-2]
Name: EMD_NM, dtype: object

In [283]:
dong = alarm['EMD_NM'].str.split(" ", expand=True) # expand = True 데이터 프레임 형태로 저장
dong

        0    1       2     3
0     남산면  창촌리   145-1  None
1     남산면  창촌리   147-1  None
2     남산면  창촌리   126-9  None
3     남산면  창촌리  219-15  None
4     남산면  창촌리   238-2  None
...   ...  ...     ...   ...
7249  귀래면  주포리   406-1  None
7250  귀래면  귀래리   244-1  None
7251  귀래면  귀래리    1222  None
7252  귀래면  귀래리    1261  None
7253  귀래면  귀래리    1349  None

[7254 rows x 4 columns]

In [284]:
# 동의 첫번째 열을 EMD_NM로 지정
alarm['EMD_NM'] = dong[0]
alarm.head()

,시설번호,시설유형코드,시군구명,시군구코드,소재지지번주소,위도,경도,안전센터명,보호틀유무,사용가능여부,설치연도,배관깊이,출수압력,배관지름,관할기관명,데이터기준일자,EMD_NM
0,강촌001호,1,춘천시,42110,강원도 춘천시 남산면 창촌리 145-1,37.786189,127.649237,강촌안전센터,N,Y,2007,0.7,7.0,100,춘천소방서,2021-11-19,남산면
1,강촌002호,1,춘천시,42110,강원도 춘천시 남산면 창촌리 147-1,37.786725,127.647929,강촌안전센터,N,Y,2013,0.7,8.0,100,춘천소방서,2021-11-19,남산면
2,강촌003호,1,춘천시,42110,강원도 춘천시 남산면 창촌리 126-9,37.785523,127.646686,강촌안전센터,Y,Y,2013,0.7,8.0,100,춘천소방서,2021-11-19,남산면
3,강촌004호,1,춘천시,42110,강원도 춘천시 남산면 창촌리 219-15,37.784756,127.643488,강촌안전센터,Y,Y,2013,0.8,8.0,100,춘천소방서,2021-11-19,남산면
4,강촌005호,1,춘천시,42110,강원도 춘천시 남산면 창촌리 238-2,37.781550,127.643992,강촌안전센터,Y,Y,2013,0.7,5.5,100,춘천소방서,2021-11-19,남산면

In [285]:
alarm['EMD_NM'].unique() # 일부 동이 띄어쓰기가 안되있어서 나누어 지지않음

array(['남산면', '남면', '신동면', '서면', '석사동', '동산면', '퇴계동', '동내면', '퇴계도', '운교동',
       '소양로3가', '낙원동', '소양로4가', '중앙로1가', '중앙로2가', '근화동', '죽림동', '조양동',
       '중앙로3가', '약사동', '소양로1가', '중앙로', '옥천동', '교동', '봉의동', '요선동', '소양로2가',
       '효자동', '신북읍', '신동', '사농동', '우두동', '사북면', '북산면', '온의동', '삼천동',
       '칠전동', '송암동', '후평동', '동면', '동면장학리', '횡성읍', '갑천면', '공근면', '서원면',
       '둔내면', '청일면', '우천면', '안흥면', '강림면', '노학동', '금호동', '중앙동', '청학동',
       '청호동', '설악동', '도문동', '대포동', '대포동957', '장사동', '영랑동', '동명동', '홍천읍',
       '화촌면', '두촌면', '북방면', '영귀미면', '서석면', '내면', '내촌면', '영월읍', '북면',
       '주천면', '한반도면', '중동면', '상동읍', '김삿갓면', '평창읍', '미탄면', '대화면', '방림면',
       '봉평면', '용평면', '진부면', '대관령면', '갈말읍', '김화읍', '근남면', '근북면', '철원읍',
       '동송읍', '화천읍', '상서면', '하남면', '화처읍', '간동면', '사내면', '양구읍', '국토정중앙면',
       '방산면', '해안면', '인제읍', '기린면', '서화면', '상남면', '간성읍', '죽왕면', '토성면',
       '죽왕면인정리', '거진읍', '현내면', '양양읍', '손양면', '강현면', '현남면', '현북면', '안현동',
       '저동', '강문동', '초당동', '운정동', '난곡동', '죽헌동933-17', '죽헌동', '지변동', '사천면',
       '대전동', '내곡동', '노암동', '유산동', '구정면', '담산동', '회산동', '성산면', '운산동',
       '신석동', '박월동', '왕산면', '옥계면', '강동면', '입암동', '임압동', '두산동', '포남동',
       '포남동1097-21', '유천동', '홍제동', '교동1899-1', '임당동', '용강동', '금학동', '성남동',
       '금학동7-3', '성남동101-6', '성남동111-4', '성남동113-10', '남문동', '성내동', '명주동',
       '주문진읍', '연곡면', '송정동', '견소동', '병산동', '남항진동', '천곡동', '평릉동', '부곡동',
       '발한동', '발한동23-8', '묵호진동2-447', '묵호진동', '망상동', '어달동', '대진동',
       '발한동309-9', '초구동', '만우동', '심곡동', '괴란동', '동회동', '쇄운동', '나안동', '효가동',
       '용정동', '이로동', '삼화동', '이로동102-1', '이로동194', '신흥동', '지흥동',
       '구미동482-1', '북평동12-8', '북평동', '구미동', '이원동', '추암동', '구호동', '대구동',
       '단봉동', '이도동', '지가동', '봉오동', '동정동', '정선읍', '화암면', '북평면', '신동읍',
       '고한읍', '임계면', '여량면', '사북읍', '황지동', '장성동', '금천동', '문곡동', '소도동',
       '철암동', '동점동', '화전동', '통동', '백산동', '창죽동', '당저동', '성북동', '원당동',
       '자원동', '남양동', '읍상동', '오사동', '건지동', '갈천동', '읍중동', '마달동', '등봉동',
       '마평동', '시우지동', '증산동', '도경동', '미로면', '적노동', '오분동', '정상동', '정하동',
       '사직동', '조비동', '도계읍', '근덕면', '노곡면', '원덕읍', '하장면', '봉산동', '반곡동',
       '관설동', '행구동', '평원동', '학성동', '일산동', '원동', '인동', '단계동', '단구동',
       '단구동1567', '단구동1568-1', '단구동1579-7', '단구동1588-1', '명륜동', '개운동',
       '신림면', '판부면', '우산동', '호저면', '만종리', '태장동', '가현동', '태장동129-3', '소초면',
       '문막읍', '부론면', '지정면', '무실동', '흥업면', '귀래면'], dtype=object)

In [286]:
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace(pat=r'[^\w]', repl=r'', regex=True) # 특수문자 제거

In [287]:
alarm['EMD_NM'].unique() # 숫자를 정규표현식을 이용하려 했지만 중앙로 n가 등 특수한 경우가 존재하여 제거 X  하나하나 지워야겠음

array(['남산면', '남면', '신동면', '서면', '석사동', '동산면', '퇴계동', '동내면', '퇴계도', '운교동',
       '소양로3가', '낙원동', '소양로4가', '중앙로1가', '중앙로2가', '근화동', '죽림동', '조양동',
       '중앙로3가', '약사동', '소양로1가', '중앙로', '옥천동', '교동', '봉의동', '요선동', '소양로2가',
       '효자동', '신북읍', '신동', '사농동', '우두동', '사북면', '북산면', '온의동', '삼천동',
       '칠전동', '송암동', '후평동', '동면', '동면장학리', '횡성읍', '갑천면', '공근면', '서원면',
       '둔내면', '청일면', '우천면', '안흥면', '강림면', '노학동', '금호동', '중앙동', '청학동',
       '청호동', '설악동', '도문동', '대포동', '대포동957', '장사동', '영랑동', '동명동', '홍천읍',
       '화촌면', '두촌면', '북방면', '영귀미면', '서석면', '내면', '내촌면', '영월읍', '북면',
       '주천면', '한반도면', '중동면', '상동읍', '김삿갓면', '평창읍', '미탄면', '대화면', '방림면',
       '봉평면', '용평면', '진부면', '대관령면', '갈말읍', '김화읍', '근남면', '근북면', '철원읍',
       '동송읍', '화천읍', '상서면', '하남면', '화처읍', '간동면', '사내면', '양구읍', '국토정중앙면',
       '방산면', '해안면', '인제읍', '기린면', '서화면', '상남면', '간성읍', '죽왕면', '토성면',
       '죽왕면인정리', '거진읍', '현내면', '양양읍', '손양면', '강현면', '현남면', '현북면', '안현동',
       '저동', '강문동', '초당동', '운정동', '난곡동', '죽헌동93317', '죽헌동', '지변동', '사천면',
       '대전동', '내곡동', '노암동', '유산동', '구정면', '담산동', '회산동', '성산면', '운산동',
       '신석동', '박월동', '왕산면', '옥계면', '강동면', '입암동', '임압동', '두산동', '포남동',
       '포남동109721', '유천동', '홍제동', '교동18991', '임당동', '용강동', '금학동', '성남동',
       '금학동73', '성남동1016', '성남동1114', '성남동11310', '남문동', '성내동', '명주동',
       '주문진읍', '연곡면', '송정동', '견소동', '병산동', '남항진동', '천곡동', '평릉동', '부곡동',
       '발한동', '발한동238', '묵호진동2447', '묵호진동', '망상동', '어달동', '대진동',
       '발한동3099', '초구동', '만우동', '심곡동', '괴란동', '동회동', '쇄운동', '나안동', '효가동',
       '용정동', '이로동', '삼화동', '이로동1021', '이로동194', '신흥동', '지흥동', '구미동4821',
       '북평동128', '북평동', '구미동', '이원동', '추암동', '구호동', '대구동', '단봉동', '이도동',
       '지가동', '봉오동', '동정동', '정선읍', '화암면', '북평면', '신동읍', '고한읍', '임계면',
       '여량면', '사북읍', '황지동', '장성동', '금천동', '문곡동', '소도동', '철암동', '동점동',
       '화전동', '통동', '백산동', '창죽동', '당저동', '성북동', '원당동', '자원동', '남양동',
       '읍상동', '오사동', '건지동', '갈천동', '읍중동', '마달동', '등봉동', '마평동', '시우지동',
       '증산동', '도경동', '미로면', '적노동', '오분동', '정상동', '정하동', '사직동', '조비동',
       '도계읍', '근덕면', '노곡면', '원덕읍', '하장면', '봉산동', '반곡동', '관설동', '행구동',
       '평원동', '학성동', '일산동', '원동', '인동', '단계동', '단구동', '단구동1567',
       '단구동15681', '단구동15797', '단구동15881', '명륜동', '개운동', '신림면', '판부면',
       '우산동', '호저면', '만종리', '태장동', '가현동', '태장동1293', '소초면', '문막읍', '부론면',
       '지정면', '무실동', '흥업면', '귀래면'], dtype=object)

In [288]:
# 전처리시 문제가 있던행을 변경
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('죽헌동93317', '죽헌동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('교동18991', '교동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('금학동73', '금학동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('성남동1016', '성남동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('성남동1114', '성남동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('성남동11310', '성남동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('발한동3099', '발한동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('이로동1021', '이로동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('이로동194', '이로동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('구미동4821', '구미동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('단구동1567', '단구동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('단구동15797', '단구동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('단구동15881', '단구동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('태장동1293', '태장동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('대포동957', '대포동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('포남동109721', '포남동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('발한동238', '발한동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('묵호진동2447', '목호진동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('단구동15681', '단구동')
alarm['EMD_NM'] = alarm['EMD_NM'].str.replace('북평동128', '북평동')

In [289]:
# 필요없는 데이터 제거
del alarm['시설유형코드']
del alarm['시설번호']
del alarm['시군구코드']
del alarm['데이터기준일자']

In [290]:
# alarm.to_csv('소방용수시설.csv', encoding='cp949')
# df.to_csv('화재발생위치.csv', encoding='cp949')

---

## 하나의 데이터로 만들기

In [291]:
# 개수를 데이터프레임으로 변환
water = pd.DataFrame(alarm['EMD_NM'].value_counts())
fire = pd.DataFrame(df['EMD_NM'].value_counts())

In [292]:
water

        EMD_NM
홍천읍        183
남면         156
교동         155
서면         148
횡성읍        141
...        ...
적노동          1
오분동          1
죽왕면인정리       1
조비동          1
운산동          1

[264 rows x 1 columns]

In [293]:
# 인덱스를 초기화
water = water.reset_index()
fire = fire.reset_index()

In [294]:
water.rename(columns={'EMD_NM':'용수시설개수'}, inplace=True)
fire.rename(columns={'EMD_NM':'화재발생횟수'}, inplace=True)

In [295]:
# # 공통된 행 합치기(index 기준으로)
dat = pd.merge(water, fire, on = 'index') 

dat.rename(columns={'index':'EMD_NM'}, inplace=True)

dat

    EMD_NM  용수시설개수  화재발생횟수
0      홍천읍     183      63
1       남면     156      84
2       교동     155     129
3       서면     148      81
4      횡성읍     141      62
..     ...     ...     ...
223    갈천동       1       7
224    마달동       1       2
225    적노동       1       1
226    오분동       1       1
227    운산동       1       3

[228 rows x 3 columns]

In [296]:
# # 시군구 추가 (이상하면 제거)

# SGG_NM = alarm[['시군구명', 'EMD_NM']]
# dat = pd.merge(dat, SGG_NM, on='EMD_NM')
# dat = dat.drop_duplicates(keep='first')

---

## 필요한 파생변수 생성

- EMD_NM 별 평균화재도착시간 (화재발생도착시간 - 화재발생출동시간)

    출동시	출동분

    DSP_HOUR	DSP_MIN

    현장도착시	현장도착분

    SPT_ARVL_HOUR	SPT_ARVL_MIN

In [297]:
# 위에서 결측값이 있는데 제거했더니 도착시간이 안나와서 새로 load
df = pd.read_csv('./data/구조 종별 신고.재난 데이터.csv', encoding= 'utf-8')

# 데이터 화재관련 값만 추출

df = df[(df['ACDNT_CAUSE'] == '기타화재') | (df['ACDNT_CAUSE'] == '화약류') | (df['ACDNT_CAUSE'] == '방화')
        | (df['ACDNT_CAUSE'] == '폭발물') | (df['ACDNT_CAUSE'] == '화재확인')]

In [298]:
# 시간*60 + 분으로 해서 하나의 데이터로 만들었음
s_time = (df['DSP_HOUR']*60) + (df['DSP_MIN'])
a_time = (df['SPT_ARVL_HOUR']*60) + (df['SPT_ARVL_MIN'])

In [299]:
# 도착시간에 결측치가 있어서 0분으로 처리
a_time = a_time.fillna(s_time)

In [300]:
# 걸린시간
time = a_time - s_time

time = pd.DataFrame(time)

In [301]:
df['time'] = time

In [302]:
# EMD_NM 별 화재도착시간 만들기
# 평균화재도착시간으로 하려했는데 23시출발 - 0시 도착이면 값이 이상해져서 중앙값으로 하였음.
time = pd.DataFrame(df.groupby(df['EMD_NM'])['time'].median())
time = time.reset_index()
time

    EMD_NM  time
0      가곡면   5.0
1      가현동   3.0
2      간동면   9.0
3      간성읍   8.0
4      갈말읍   6.0
..     ...   ...
232    횡성읍   5.0
233    효가동   5.0
234    효자동   4.0
235    후평동   4.0
236    흥업면   8.0

[237 rows x 2 columns]

In [303]:
dat = pd.merge(dat, time, on='EMD_NM')
dat

    EMD_NM  용수시설개수  화재발생횟수  time
0      홍천읍     183      63   5.0
1       남면     156      84   9.0
2       교동     155     129   4.0
3       서면     148      81  10.0
4      횡성읍     141      62   5.0
..     ...     ...     ...   ...
223    갈천동       1       7   5.0
224    마달동       1       2   8.0
225    적노동       1       1   8.0
226    오분동       1       1   0.0
227    운산동       1       3  14.0

[228 rows x 4 columns]

---

#### SPT_FRSTT_DIST(거리)

    - 화재발생위치로 부터의 거리

In [304]:
fire = pd.read_csv('./data/화재 종별 신고.재난 데이터.csv', encoding='utf-8')
fire.head()

,MSFRTN_RESC_REPRT_NO,ACDNT_CAUSE,PRCS_RESULT_SE_NM,DCLR_YMD,DCLR_TM,DCLR_YR,SEASON_SE_NM,QTR_SE,DCLR_MNTH,DCLR_DAY,...,ACDNT_PLACE_NM,ACDNT_PLACE_DETAIL_NM,ACDNT_CAUSE_ASORT_NM,TIME_UNIT_TMPRT,TIME_UNIT_WS,TIME_UNIT_WD,TIME_UNIT_HUMIDITY,FRSTT_NM,WARD_NM,LFDAU_NM
0,20204201103M00003,작동기기,안전조치,20200101,15418,2020,겨울,1,1,1,...,공동주택,다세대주택,부주의,-8,360.0,2.0,51,춘천소방서,효자119안전센터,NaN
1,20204202104M00003,미상,안전조치,20200101,91144,2020,겨울,1,1,1,...,기타건축물,기타 건축물,미상,-6,45.0,2.0,75,원주소방서,단구119안전센터,NaN
2,20204203108M00007,"불꽃, 불티",안전조치,20200101,125616,2020,겨울,1,1,1,...,산불,사유림,부주의,6,225.0,18.0,34,강릉소방서,유천119안전센터,NaN
3,20204203103M00007,"마찰, 전도, 복사",안전조치,20200101,145024,2020,겨울,1,1,1,...,단독주택,단독주택,부주의,6,270.0,2.0,29,강릉소방서,주문진119안전센터,NaN
4,20204209107M00003,작동기기,안전조치,20200101,155021,2020,겨울,1,1,1,...,일반업무,기타 일반업무시설,전기적 요인,1,270.0,6.5,60,영월소방서,영월119안전센터,NaN

In [305]:
dist = pd.DataFrame(fire.groupby(fire['EMD_NM'])['SPT_FRSTT_DIST'].mean())
dist = dist.reset_index()
dist

    EMD_NM  SPT_FRSTT_DIST
0      가곡면       55.800000
1      가현동       14.000000
2      간동면       18.916667
3      간성읍        6.851852
4      갈말읍        5.636364
..     ...             ...
221    횡성읍        4.800000
222    효가동        4.750000
223    효자동        2.937500
224    후평동        1.222222
225    흥업면       12.782609

[226 rows x 2 columns]

In [306]:
dat = pd.merge(dat, dist, on='EMD_NM')
dat

    EMD_NM  용수시설개수  화재발생횟수  time  SPT_FRSTT_DIST
0      홍천읍     183      63   5.0        4.380952
1       남면     156      84   9.0       18.781250
2       교동     155     129   4.0        2.541667
3       서면     148      81  10.0       23.227273
4      횡성읍     141      62   5.0        4.800000
..     ...     ...     ...   ...             ...
207    박월동       1       9   8.0        7.250000
208    건지동       1       3   9.0        4.000000
209    갈천동       1       7   5.0        5.333333
210    마달동       1       2   8.0        2.000000
211    운산동       1       3  14.0        7.000000

[212 rows x 5 columns]

---

#### 배관깊이, 출수압력, 배관지름

In [307]:
alarm

,시군구명,소재지지번주소,위도,경도,안전센터명,보호틀유무,사용가능여부,설치연도,배관깊이,출수압력,배관지름,관할기관명,EMD_NM
0,춘천시,강원도 춘천시 남산면 창촌리 145-1,37.786189,127.649237,강촌안전센터,N,Y,2007,0.7,7.0,100,춘천소방서,남산면
1,춘천시,강원도 춘천시 남산면 창촌리 147-1,37.786725,127.647929,강촌안전센터,N,Y,2013,0.7,8.0,100,춘천소방서,남산면
2,춘천시,강원도 춘천시 남산면 창촌리 126-9,37.785523,127.646686,강촌안전센터,Y,Y,2013,0.7,8.0,100,춘천소방서,남산면
3,춘천시,강원도 춘천시 남산면 창촌리 219-15,37.784756,127.643488,강촌안전센터,Y,Y,2013,0.8,8.0,100,춘천소방서,남산면
4,춘천시,강원도 춘천시 남산면 창촌리 238-2,37.781550,127.643992,강촌안전센터,Y,Y,2013,0.7,5.5,100,춘천소방서,남산면
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249,원주시,강원도 원주시 귀래면 주포리 406-1,37.160311,127.857480,흥업안전센터,Y,Y,2019,1.4,6.0,100,원주소방서,귀래면
7250,원주시,강원도 원주시 귀래면 귀래리 244-1,37.223570,127.894349,흥업안전센터,Y,Y,2017,1.0,3.0,100,원주소방서,귀래면
7251,원주시,강원도 원주시 귀래면 귀래리 1222,37.220482,127.865188,흥업안전센터,Y,Y,2016,1.0,5.0,100,원주소방서,귀래면
7252,원주시,강원도 원주시 귀래면 귀래리 1261,37.221834,127.864116,흥업안전센터,Y,Y,2016,1.0,5.0,100,원주소방서,귀래면
7253,원주시,강원도 원주시 귀래면 귀래리 1349,37.223992,127.864142,흥업안전센터,Y,Y,2016,1.0,5.0,100,원주소방서,귀래면

In [308]:
depth = pd.DataFrame(alarm.groupby(alarm['EMD_NM'])['배관깊이'].mean())
depth = depth.reset_index()
depth

    EMD_NM      배관깊이
0      가현동  1.000000
1      간동면  1.066667
2      간성읍  1.000000
3      갈말읍  1.200000
4      갈천동  1.500000
..     ...       ...
259    횡성읍  1.007092
260    효가동  0.525152
261    효자동  0.948913
262    후평동  0.844681
263    흥업면  0.731579

[264 rows x 2 columns]

In [309]:
pressure = pd.DataFrame(alarm.groupby(alarm['EMD_NM'])['출수압력'].mean())
pressure = pressure.reset_index()
pressure

    EMD_NM      출수압력
0      가현동  5.460000
1      간동면  3.333333
2      간성읍  3.265455
3      갈말읍  4.261176
4      갈천동  6.500000
..     ...       ...
259    횡성읍  5.184397
260    효가동  5.593939
261    효자동  5.294565
262    후평동  5.357447
263    흥업면  5.589474

[264 rows x 2 columns]

In [310]:
diameter = pd.DataFrame(alarm.groupby(alarm['EMD_NM'])['배관지름'].mean())
diameter = diameter.reset_index()
diameter

    EMD_NM        배관지름
0      가현동  100.000000
1      간동면  100.000000
2      간성읍  100.000000
3      갈말읍  100.000000
4      갈천동   75.000000
..     ...         ...
259    횡성읍   65.000000
260    효가동   75.000000
261    효자동   99.184783
262    후평동  100.000000
263    흥업면  100.000000

[264 rows x 2 columns]

In [311]:
dat = pd.merge(dat, depth, on='EMD_NM')
dat

    EMD_NM  용수시설개수  화재발생횟수  time  SPT_FRSTT_DIST      배관깊이
0      홍천읍     183      63   5.0        4.380952  0.997268
1       남면     156      84   9.0       18.781250  0.884615
2       교동     155     129   4.0        2.541667  1.060000
3       서면     148      81  10.0       23.227273  1.022297
4      횡성읍     141      62   5.0        4.800000  1.007092
..     ...     ...     ...   ...             ...       ...
207    박월동       1       9   8.0        7.250000  1.200000
208    건지동       1       3   9.0        4.000000  1.500000
209    갈천동       1       7   5.0        5.333333  1.500000
210    마달동       1       2   8.0        2.000000  1.500000
211    운산동       1       3  14.0        7.000000  1.000000

[212 rows x 6 columns]

In [312]:
dat = pd.merge(dat, pressure, on='EMD_NM')
dat = pd.merge(dat, diameter, on='EMD_NM')

In [313]:
dat

,EMD_NM,용수시설개수,화재발생횟수,time,SPT_FRSTT_DIST,배관깊이,출수압력,배관지름
0,홍천읍,183,63,5.0,4.380952,0.997268,4.621311,100.000000
1,남면,156,84,9.0,18.781250,0.884615,4.489103,93.205128
2,교동,155,129,4.0,2.541667,1.060000,4.325161,99.548387
3,서면,148,81,10.0,23.227273,1.022297,4.902703,94.560811
4,횡성읍,141,62,5.0,4.800000,1.007092,5.184397,65.000000
...,...,...,...,...,...,...,...,...
207,박월동,1,9,8.0,7.250000,1.200000,3.900000,100.000000
208,건지동,1,3,9.0,4.000000,1.500000,4.000000,100.000000
209,갈천동,1,7,5.0,5.333333,1.500000,6.500000,75.000000
210,마달동,1,2,8.0,2.000000,1.500000,6.500000,100.000000
211,운산동,1,3,14.0,7.000000,1.000000,4.000000,100.000000

---

In [314]:
# dat = pd.merge(dat, pressure, on='EMD_NM')
# people = pd.read_csv('./data/강원도_읍면동별_주민등록인구.csv', encoding='cp949')
# people

# del people['5세별']
# del people['남자인구수 (명)']
# del people['여자인구수 (명)']

# people.rename(columns={'행정구역(동읍면)별':'EMD_NM'}, inplace=True)
# people.head()

# dat = pd.merge(dat, people, on='EMD_NM')
# dat